name: Run authotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps: 
      - name: Copy sourse code
        uses: action/checkout@v4
      - name: Set up Python enc
        uses: action/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
